In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
inp0 = pd.read_csv('Cricket.csv', encoding='ISO-8859-1')
print(inp0.shape)
inp0.head()

(79, 13)

,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0
0,SR Tendulkar (INDIA),1989-2012,463,452,41,18426,200*,44.83,21367,86.23,49,96,20
1,KC Sangakkara (Asia/ICC/SL),2000-2015,404,380,41,14234,169,41.98,18048,78.86,25,93,15
2,RT Ponting (AUS/ICC),1995-2012,375,365,39,13704,164,42.03,17046,80.39,30,82,20
3,ST Jayasuriya (Asia/SL),1989-2011,445,433,18,13430,189,32.36,14725,91.20,28,68,34
4,DPMD Jayawardene (Asia/SL),1998-2015,448,418,39,12650,144,33.37,16020,78.96,19,77,28

In [3]:
inp1 = inp0[[
    'SR',
    'Ave'
]]

In [24]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

data_scaled = scaler.fit_transform(inp1)
data_scaled = pd.DataFrame(data_scaled, columns=[inp1.columns])
data_scaled.head()

         SR       Ave
0  0.703152  1.072294
1 -0.044139  0.587725
2  0.110997  0.596226
3  1.207091 -1.047909
4 -0.034000 -0.876185

In [25]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=4,max_iter=500, random_state=100)
kmeans.fit(data_scaled)

KMeans(max_iter=500, n_clusters=4, random_state=100)

In [21]:
condition = inp0['Player'].str.contains('ayl')
inp0[condition]

,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0
17,CH Gayle (ICC/WI),1999-2015,269,264,17,9221,215,37.33,10834,85.11,22,47,23
46,LRPL Taylor (NZ),2006-2017,190,176,29,6486,131*,44.12,7906,82.03,17,37,9
69,BRM Taylor (ZIM),2004-2015,167,166,15,5258,145*,34.82,7060,74.47,8,32,13

In [26]:
data_inverse_scaled = scaler.inverse_transform(data_scaled)
data_inverse_scaled = pd.DataFrame(data_inverse_scaled, columns=['SR', 'Ave'])
data_inverse_scaled['cluster'] = kmeans.labels_
data_inverse_scaled

       SR    Ave  cluster
0   86.23  44.83        2
1   78.86  41.98        2
2   80.39  42.03        2
3   91.20  32.36        3
4   78.96  33.37        1
..    ...    ...      ...
74  64.92  45.03        2
75  73.75  43.40        2
76  76.98  35.36        1
77  92.44  39.75        2
78  81.25  29.70        1

[79 rows x 3 columns]

In [27]:
condition = data_inverse_scaled['cluster'] == 0
inp0[condition]

,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0
13,MS Dhoni (Asia/INDIA),2004-2017,295,255,70,9496,183*,51.32,10706,88.69,10,64,8
15,AB de Villiers (Afr/SA),2005-2017,222,213,39,9319,162*,53.55,9295,100.25,24,53,7
25,V Kohli (INDIA),2008-2017,188,180,29,8146,183,53.94,8952,90.99,27,43,11
34,HM Amla (SA),2008-2017,156,153,10,7186,159,50.25,8069,89.05,25,33,3
38,MG Bevan (AUS),1994-2004,232,196,67,6912,108*,53.58,9320,74.16,6,46,5
42,IVA Richards (WI),1975-1991,187,167,24,6721,189*,47.00,7451,90.20,11,45,7
64,MEK Hussey (AUS),2004-2012,185,157,44,5442,109*,48.15,6243,87.16,3,39,3

In [28]:
inp0['cluster'] = kmeans.labels_

In [47]:
condition = inp0['Player'].str.contains('ravi')
inp0[condition]

,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,cluster
8,R Dravid (Asia/ICC/INDIA),1996-2011,344,318,40,10889,153,39.16,15284,71.24,12,83,13,1

In [49]:
inp0.iloc[[42,0,8,17,63],:]

,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,cluster
42,IVA Richards (WI),1975-1991,187,167,24,6721,189*,47.00,7451,90.20,11,45,7,0
0,SR Tendulkar (INDIA),1989-2012,463,452,41,18426,200*,44.83,21367,86.23,49,96,20,2
8,R Dravid (Asia/ICC/INDIA),1996-2011,344,318,40,10889,153,39.16,15284,71.24,12,83,13,1
17,CH Gayle (ICC/WI),1999-2015,269,264,17,9221,215,37.33,10834,85.11,22,47,23,2
63,MJ Guptill (NZ),2009-2017,146,143,16,5500,237*,43.30,6269,87.73,12,32,12,2

In [39]:
inp0.head()

,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,cluster
0,SR Tendulkar (INDIA),1989-2012,463,452,41,18426,200*,44.83,21367,86.23,49,96,20,2
1,KC Sangakkara (Asia/ICC/SL),2000-2015,404,380,41,14234,169,41.98,18048,78.86,25,93,15,2
2,RT Ponting (AUS/ICC),1995-2012,375,365,39,13704,164,42.03,17046,80.39,30,82,20,2
3,ST Jayasuriya (Asia/SL),1989-2011,445,433,18,13430,189,32.36,14725,91.20,28,68,34,3
4,DPMD Jayawardene (Asia/SL),1998-2015,448,418,39,12650,144,33.37,16020,78.96,19,77,28,1

In [22]:
data_inverse_scaled.iloc[17,:]

SR         85.11
Ave        37.33
cluster     2.00
Name: 17, dtype: float64

In [ ]:
yuvraj = 2
tendulkar = 2
gayle = 2
jayasuriya = 3